config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  get '/about' => 'pages#about'

  get 'children/index'

  get 'children/show'

  get 'children/create'

  get 'children/update'

  get 'sections/show'

  get 'sections/index'

  mount Attachinary::Engine => "/attachinary"

  get 'photos/new'

  get 'photos/create'

  get 'photos/update'

  get 'photos/edit'

  get 'photos/destroy'

  # devise_for :users
  devise_for :users, controllers: {
    registrations: "registrations", 
    sessions: "sessions"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :profiles, except: [:destroy]

  post 'global_search', to: 'invoices#index'

  resources :invoices, except: [:destroy] do
    member do
      post 'paid', to: 'invoices#paid'
      post 'unpaid', to: 'invoices#unpaid'
    end
    collection do
      post 'markaspaid'
    end
  end

  resources :events
  resources :albums
  resources :sections
  resources :children do
    member do
      post 'approve', to: 'children#approve'
    end
  end

  resources :messages, only: [:new, :create, :index]
end

app/models/message.rb
class Message < ApplicationRecord
  validates :subject, presence: true
  validates :body, presence: true

  attr_accessor :section

  belongs_to :admin
  belongs_to :profile
  belongs_to :section

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    create_message
    if @message.save
      flash[:notice] = "Message successfully created"
      redirect_to messages_path
    else
      flash[:notice] = "Message not created"
      render :new
    end
  end

  private

  def set_message
    @message = Message.find(params[:id])
  end

  def create_message
    Profile.where(section_id: message_params[:section_id]).each do |profile|
      if profile.user != current_user
        @message = Message.new(message_params)
        @message.admin = current_user.profile.admin
        @message.profile = profile
        if @message.save
          @message.save
          UserMailer.custom_message(@message.profile.user, @message).deliver_now
        end

      end
    end
  end

  def message_params
    params.require(:message).permit(:profile_id, :subject, :body, :admin_id, :section_id)
  end
end

app/views/messages/index.html.erb
<% if current_user.profile.admin %>
<h1 class="text-center"> Messages </h1>

<main id="messages" class="table table-hover">
	<%= link_to "", new_message_path, class: "fa fa-plus-circle new-btn", id: "plus" %>
	<table >
		<thead>
			<tr>
				<th>Section</th>
				<th>Subject</th>
				<th id="sms">Message</th>
			</tr>
		</thead>
		<tbody>
	  			<% Message.all.uniq.pluck(:subject, :body, :section_id).each do |message| %>
			<tr>
			     <td><%= Section.find_by_id(message[2]).name %></td>
			     <td><%= message[0] %></td>
			     <td><%= message[1] %></td>
			    <% end %>
			</tr>
		</tbody>
	</table>
</main>
<% else %>
<%= render "shared/taboo" %>
<% end %>

app/views/messages/new.html.erb
<% if current_user.profile.admin %>
  <div class="container">
  <div class="forms">
    <% if @message.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= simple_form_for [@message] do |f| %>
    <%= f.input :section_id, collection: Section.all %>
    <%= f.input :subject %>
    <%= f.input :body, label: false, as: :text, autofocus: true, :input_html => {:style => 'width: 100%', :rows => 5, class: 'response-project'} %>
    <%= f.submit "generate message", class: "btn"%>
    <% end %>
  </div>
</div>
</div>
<% else %>
<%= render "shared/taboo" %>
<% end %>