config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  get '/about' => 'pages#about'

  get 'children/index'

  get 'children/show'

  get 'children/create'

  get 'children/update'

  get 'sections/show'

  get 'sections/index'

  mount Attachinary::Engine => "/attachinary"

  get 'photos/new'

  get 'photos/create'

  get 'photos/update'

  get 'photos/edit'

  get 'photos/destroy'

  # devise_for :users
  devise_for :users, controllers: {
    registrations: "registrations", 
    sessions: "sessions"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :profiles, except: [:destroy]

  post 'global_search', to: 'invoices#index'

  resources :invoices, except: [:destroy] do
    member do
      post 'paid', to: 'invoices#paid'
      post 'unpaid', to: 'invoices#unpaid'
    end
    collection do
      post 'markaspaid'
    end
  end

  resources :events
  resources :albums
  resources :sections
  resources :children do
    member do
      post 'approve', to: 'children#approve'
    end
  end

  resources :messages, only: [:new, :create, :index]
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :invoices
  has_one :admin
  has_many :messages
  belongs_to :section
  has_many :events
  has_many :children
  has_attachment :photo


  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birth_date, presence: true
  validates :address, presence: true
  validates :zip_code, presence: true
  validates :city, presence: true
  validates :phone_number, presence: true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update]

  def index
    @profiles = Profile.all
      respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="all_profiles.xlsx"'
      }
    end
  end


  def show
    @events = Event.all
    @invoices = Invoice.all
    @child = Child.new
    # @child = Child.find(params[:id])
  end

  def new
    @profile = Profile.new
    @disable_footer = true
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    if @profile.save
      redirect_to new_child_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @profile.update(profile_params)
    redirect_to profile_path(@profile)
  end

  private

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :totem, :birth_date, :address, :zip_code, :city, :country, :phone_number, :photo, :gender, :comment)
  end

  def set_profile
    @profile = Profile.find(params[:id])
  end
end

app/views/profiles/_form.html.erb
<div class="new-modal modal fade" id="editprofileModal" tabindex="-1" role="dialog" aria-labelledby="editprofileModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editprofileModalLabel">Edit profile</h5>
      </div>
      <div class="modal-body">

        <%= simple_form_for(@profile, html: {id: :msform}) do |f| %>
        <%=  f.error_notification %>
        <div class="form-fields">
          <%= f.input :first_name %>
          <%= f.input :last_name %>
          <%= f.input :totem %>
          <%= f.input :birth_date %>
          <%= f.input :address %>
          <%= f.input :zip_code %>
          <%= f.input :city %>
          <%= f.input :phone_number %>
          <%= f.input :gender %>
          <%= f.input :comment %>
          <%= f.input :photo, as: :attachinary %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close
        </button>
        <%= f.button :submit , "Save changes", class: "submit-btn"%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<%= render "form" %>

app/views/profiles/index.html.erb
<% if current_user.profile.admin %>
  <%= content_for(:after_js) do %>
  <h1 class="text-center">Users</h1>
    <main class="profile-tab invoice-tab-box">

      <div class="tabs-bar">
<!-- tabs -->
        <span>
          <% Section.all.each do |section| %>
          <button class="tabs-bar-item tab-button" onclick="openTab('<%= section.name %>')"><%= section.name %></button>
          <% end %>
          <button class="tabs-bar-item tab-button" onclick="openTab('pending')">Pending</button>
          <button class="tabs-bar-item tab-button" onclick="openTab('all')">All</button>
        </span>
      </div>

        <% Section.all.each do |section| %>
          <div id='<%= section.name %>' class="tab" style="display:none">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Birthday</th>
                </tr>
              </thead>
              <tbody>
                <% Child.where(section_id: section.id).where(status: "Accepted").each do |child| %>
                  <tr>
                    <td> <%= child.first_name %> </td>
                    <td> <%= child.last_name %></td>
                    <td> <%= child.birthday %> </td>
                    <td> <%= link_to "edit", edit_child_path(child) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% end %>
        <div id='pending' class="tab" style="display:none">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Birthday</th>
                  <th>Section</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% Child.where(status: "Pending").each do |child| %>
                  <tr>
                    <td> <%= child.first_name %> </td>
                    <td> <%= child.last_name %></td>
                    <td> <%= child.birthday %> </td>
                    <td><%= Section.find_by_id(child.section_id).name  %></td>
                    <td><%= link_to "approve", approve_child_path(child.id), method: :post %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <div id='all' class="tab" style="display:none">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Birthday</th>
                  <th>Section</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% Child.all.each do |child| %>
                  <tr>
                    <td> <%= child.first_name %> </td>
                    <td> <%= child.last_name %></td>
                    <td> <%= child.birthday %> </td>
                    <td><%= Section.find_by_id(child.section_id).name  %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
  <%= link_to 'Download as .xlsx', profiles_path(format: :xlsx) %>
    </main>
</main>
<% end %>
<% else %>
<%= render "shared/taboo" %>
<% end %>

app/views/profiles/new.html.erb
<%= render 'shared/new-profile' %>

app/views/profiles/show.html.erb
<% if current_user.profile.status == "Accepted" %>
<div id="user-dashboard">

  <div id="body-box">

    <div id="bbox1">
      <h5>.</h5>
      <div class="profile-db card">
        <img class="avatar-large avatar-profile" src=" <%= cl_image_path current_user.profile.photo.path, {gravity: :face} if current_user.profile.photo %> " >
        <div class="card-header">
          <h4><strong><%= current_user.profile.first_name %> <%= current_user.profile.last_name %></strong></h4>
          <h4><%= current_user.profile.totem %></h4>
          <p>• • • • • • • • • • • • • • • • •</p>
        </div>
        <div class="card-body">
          <p><strong>EMAIL</strong></p>
          <p><%= current_user.profile.user.email %></p>
          <p><strong>BIRTH DATE</strong></p>
          <p><%= current_user.profile.birth_date %></p>
          <p><strong>ADDRESS</strong></p>
          <p><%= current_user.profile.address %>
          <p><%= current_user.profile.zip_code %> - <%= current_user.profile.city %> (<%= current_user.profile.country %>)</p>
          <p><strong>PHONE NUMBER</strong></p>
          <p><%= current_user.profile.phone_number %></p>
          <p><strong>ADDITIONAL INFORMATION</strong></p>
          <p><%= current_user.profile.comment %></p>
        </div>
        <div class="card-footer">

          <div class="edit-btn text-center" data-toggle="modal" data-target="#viewChildModal">
            <i class="fa fa-user-circle-o" aria-hidden="true"></i>
          </div>
          <!-- Modal -->
<!--           <#%= render "shared/childrensho" %>
 -->
          <div class="edit-btn text-center" data-toggle="modal" data-target="#addChildModal">
            <i class="fa fa-plus-circle" aria-hidden="true"></i></i>
          </div>
          <!-- Modal -->
          <%= render "form" %>

          <div class="edit-btn text-center" data-toggle="modal" data-target="#editprofileModal">
            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
          </div>
          <!-- Modal -->
          <%= render "shared/new-children" %>

        </div>
      </div>

    </div>

    <div id="bbox2">

      <div id="bbox21">

        <div id="bbox211">

          <h5>Calendar</h5>
          <div class="calendar-db card">
            <div class="card-body">
              <%= month_calendar events: @events, previous_link: events_ajax_previous_link, next_link: events_ajax_next_link do |date, events| %>
                <% if !events.present? %>
                  <%= date.day %>

                <%#= if day has event dont show this one date.day %>
                <% else %>
                  <!-- Modal events show -->
                <div class="modal-btn" data-toggle="modal" data-target="#eventsModal"><%= date.day %></div>

                  <div class="modal fade" id="eventsModal" tabindex="-1" role="dialog" aria-labelledby="eventsModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-sm" role="document">
                      <div class="modal-content">
                        <button type=" button" class="close close-btn" data-dismiss="modal" aria-label="Close">
                          <i class="fa fa-times" aria-hidden="true"></i>
                        </button>
                        <div class="modal-body">
                          <% events.each do |event| %>
                            <p><strong><%= event.name %></strong></p>
                            <p>Start time   <%= event.start_time.strftime("%b %e, %l:%M %p") %></p>
                            <p>End time   <%= event.end_time.strftime("%b %e, %l:%M %p") %></p>
                            <p>Description   <%= event.description %></p>
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>

        </div>

        <div id="bbox212">

          <h5>Reminders</h5>
          <div class="reminders-db card">
            <div class="card-body">
              <% @events.each do |event| %>
                <p><i class="fa fa-calendar" aria-hidden="true"></i><strong> <%= event.name %></strong> <%= event.start_time.strftime("%b %e, %l:%M %p") %></p>
              <% end %>
              <% @invoices.each do |invoice| %>
                <% if invoice.profile.user == current_user && invoice.status == "unpaid" %>
                  <p><i class="fa fa-eur" aria-hidden="true"></i><strong> <%= invoice.title %></strong> is due by <%= invoice.due_date.strftime("%b %d")%></p>
                <% end %>
              <% end %>
            </div>
          </div>

        </div>

      </div>

      <div id="bbox22">

        <h5>Photos</h5>
        <div class="photos-db">
          <div class="card-body">

            <%= render "shared/carousel" %>
          </div>
        </div>

      </div>

    </div>

  </div>

  <div id="bottom-box">

    <h5>Invoices</h5>
    <div class="invoices-db card">
      <div class="card-body">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Title</th>
              <th>Paid</th>
              <th>Pending</th>
              <th>Total</th>
              <th>Collected amount</th>
              <th>Due amount</th>
            </tr>
          </thead>
          <tbody>
            <% Invoice.uniq.pluck(:title).each_with_index do |invoice_title, i| %>
            <tr class="clickable" data-toggle="collapse" id="clickable<%= i + 1 %>" data-target="#collapsed<%= i + 1 %>">
              <td> <%= invoice_title %> </td>
              <td> <%= Invoice.where("title = ? AND status = ?", invoice_title, "paid").count %></td>
              <td> <%= Invoice.where("title = ? AND status = ?", invoice_title, "unpaid").count %></td>
              <td> <%= Invoice.where("title = ?", invoice_title).count %></td>
              <td> <%= Invoice.where("title = ? AND status = ?", invoice_title, "paid").pluck(:amount).sum %>€</td>
              <td> <%= Invoice.where("title = ? AND status = ?", invoice_title, "unpaid").pluck(:amount).sum %>€</td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

  </div>

</div>
<% else %>
<%= render "shared/pending" %>
<% end %>