config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  get '/about' => 'pages#about'

  get 'children/index'

  get 'children/show'

  get 'children/create'

  get 'children/update'

  get 'sections/show'

  get 'sections/index'

  mount Attachinary::Engine => "/attachinary"

  get 'photos/new'

  get 'photos/create'

  get 'photos/update'

  get 'photos/edit'

  get 'photos/destroy'

  # devise_for :users
  devise_for :users, controllers: {
    registrations: "registrations", 
    sessions: "sessions"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :profiles, except: [:destroy]

  post 'global_search', to: 'invoices#index'

  resources :invoices, except: [:destroy] do
    member do
      post 'paid', to: 'invoices#paid'
      post 'unpaid', to: 'invoices#unpaid'
    end
    collection do
      post 'markaspaid'
    end
  end

  resources :events
  resources :albums
  resources :sections
  resources :children do
    member do
      post 'approve', to: 'children#approve'
    end
  end

  resources :messages, only: [:new, :create, :index]
end

app/views/shared/_banner.html.erb
<div class="banner">
	<div class="image" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path 'back.jpg' %>);">
		  <div class=" banner-content">
		    <h1>Pilotis</h1>
		    <p>Let us manage your community</p>
		    <%= link_to "Learn More", about_path, class: "btn btn-primary btn-lg" %>
		  </div>
	</div>
</div>

app/views/shared/_carousel.html.erb
    <div class="row__inner">
<!-- faut ajouter la loop sur les photos -->
    <% Album.last(4).each do |album|
      album.photos.last(7).each do |photo| %>
      <div class="tile">
        <div class="tile__media">
          <img class="tile__img" src=<%= cl_image_path photo.path %> alt=""  />
        </div>
      </div>
     <% end %>
     <% end %>



    </div>

app/views/shared/_childrensho.html.erb
<div class="new-modal modal fade" id="viewChildModal" tabindex="-1" role="dialog" aria-labelledby="viewChildModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="viewChildModalLabel">View children</h5>
        <button type="button" class="close close-btn " data-dismiss="modal" aria-label="Close">
          <i class="fa fa-times" aria-hidden="true"></i>
        </button>
      </div>
      <div class="modal-body">
        <!-- !!!
        Need to loop over the children of each current user - back end team help?
        !!! -->
        <div class="child-box">
          <div class="card-header">
            <% Child.where(profile_id: current_user.profile) do |child| %>
            <h4><strong><%= child.first_name %> <%= child.last_name %></strong></h4>
            <p>• • • • • • • • • • • • • • • • •</p>
          </div>
            <p><strong>BIRTH DATE </strong>  <%= child.birthday %></p>
            <p><strong>SECTION </strong>  <%= Section.find_by_id(child.section_id).name %></p>
            <p></p>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_edit_event.html.erb
<div class="forms">
  <% if @event.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <%= simple_form_for [event], html: {id: :msform} do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :start_time , order: [:day, :month, :year], default: Time.parse('9:00')%>
  <%= f.input :end_time, order: [:day, :month, :year], default: Time.parse('17:00')%>

  <input type="hidden" name="sections[section_ids][]" value="" />

  <div class="tag">
  <input type="checkbox" value="1" name="sections[section_ids][]" id="sections_section_ids_1" />
  <label for="sections_section_ids_1">baladin</label>
    <i class="fa fa-plus"></i>
    <i class="fa fa-check"></i>
  </div>

  <div class="tag">
  <input type="checkbox" value="2" name="sections[section_ids][]" id="sections_section_ids_2" />
  <label for="sections_section_ids_2">louveteau</label>
    <i class="fa fa-plus"></i>
    <i class="fa fa-check"></i>
  </div>

  <div class="tag">
  <input type="checkbox" value="3" name="sections[section_ids][]" id="sections_section_ids_3" />
  <label for="sections_section_ids_3">éclaireur</label>
    <i class="fa fa-plus"></i>
    <i class="fa fa-check"></i>
  </div>

  <div class="tag">
  <input type="checkbox" value="4" name="sections[section_ids][]" id="sections_section_ids_4" />
  <label for="sections_section_ids_4">pionnier</label>
    <i class="fa fa-plus"></i>
    <i class="fa fa-check"></i>
  </div>

  <div class="tag">
  <input type="checkbox" value="5" name="sections[section_ids][]" id="sections_section_ids_5" />
  <label for="sections_section_ids_5">guide</label>
    <i class="fa fa-plus"></i>
    <i class="fa fa-check"></i>
  </div>

  <div class="tag">
  <input type="checkbox" value="6" name="sections[section_ids][]" id="sections_section_ids_6" />
  <label for="sections_section_ids_6">lutin</label>
    <i class="fa fa-plus"></i>
    <i class="fa fa-check"></i>
  </div>

  <div class="tag">
  <input type="checkbox" value="7" name="sections[section_ids][]" id="sections_section_ids_7" />
  <label for="sections_section_ids_7">horizon</label>
    <i class="fa fa-plus"></i>
    <i class="fa fa-check"></i>
  </div>

  <%= f.submit "GENERATE EVENT", class: "btn"%>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_invoiceform.html.erb
  <% if @invoice.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @invoice.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <%= simple_form_for @invoice, html: {id: :msform} do |f| %>

    <div class="form-fields">
      <%= f.input :title %>
      <%= f.input :date %>
      <%= f.input :due_date %>
      <%= f.input :amount %>
      <%= f.input :bank_account %>
      <%= collection_check_boxes(:sections, :section_ids, Section.all, :id, :name, prompt: true)%>
    </div>
    <div class="submit-btn">
      <%= f.submit "generate invoice", class: "btn"%>
    </div>
  <% end %>

app/views/shared/_login.html.erb
<%= simple_form_for(resource, as: resource_name, html: {id: :msform}, url: session_path(resource_name)) do |f| %>

<fieldset>
<h2>Log in</h2>
  <div class="form-inputs">
    <%= f.input :email, required: false, autofocus: true %>
    <%= f.input :password, required: false %>
    <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Log in" %>
    <%= render "devise/shared/links" %>

  </div>
</fieldset>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <% if current_user.nil? || current_user.profile.nil? %>
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>
  <% else %>
    <%= link_to profile_path(current_user.profile.id), class: "navbar-wagon-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>
  <% end  %>

  <!-- Right Navigation -->
  <% if current_user.nil? || current_user.profile.nil?%>
    <h4 class="navbar-wagon-item navbar-wagon-link">
      <%= link_to "Join Us", new_user_registration_path %>
      <%= link_to "Log in", new_user_session_path %>
    </h4>
  <% else %>
    <div class="navbar-wagon-right hidden-xs hidden-sm">
      <h4 class="navbar-wagon-item navbar-wagon-link"><%= current_user.profile.first_name.capitalize %> <%= current_user.profile.last_name %></h4>
      <!-- Profile picture with dropdown list -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.profile.photo.nil? %>
              <%= image_tag "profile.png", class: "avatar dropdown-toggle", id:"navbar-wagon-menu", data: { toggle: 'dropdown'} %>
            <%else%>
             <img class="avatar" src=" <%= cl_image_path current_user.profile.photo.path, {gravity: :face} %> " dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "Dashboard", profile_path(current_user.profile.id), class: "navbar-wagon-item navbar-wagon-link"%>
            <li>
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link"%>
            </li>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_new-children.html.erb
<div class="new-modal modal fade" id="addChildModal" tabindex="-1" role="dialog" aria-labelledby="editprofileModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editprofileModalLabel">Add a child</h5>
      </div>
      <div class="modal-body">
        <%= simple_form_for(@child, html: {id: :msform}) do |f| %>
          <%=  f.error_notification %>
        <div class="form-fields">
          <%= f.input :first_name %>
          <%= f.input :last_name %>
          <%= f.input :birthday %>
          <%= f.input :section_id, collection: Section.all %>
          <%= f.input :comment %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close
        </button>
        <%= f.button :submit , "Save changes", class: "submit-btn"%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_new-event.html.erb
<div class="container">
  <div class="forms">
    <% if @event.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>


    <%= simple_form_for [@event] do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :start_time , order: [:day, :month, :year], default: Time.parse('9:00')%>
    <%= f.input :end_time, order: [:day, :month, :year], default: Time.parse('17:00')%>
    <%= f.input :section_id, collection: Section.all %>
    <%= f.submit "generate event", class: "btn"%>
    <% end %>
  </div>
</div>
</div>

app/views/shared/_new-profile.html.erb
<div class="content">
	<%= simple_form_for(@profile, html: {id: :msform}) do |f| %>
	<%=  f.error_notification %>

	<!-- progressbar -->
	<ul id="progressbar">
		<li class="active">Personal Details</li>
		<li>Contact Details</li>
		<li>Other Details</li>
	</ul>
	<!-- fieldsets -->
	<fieldset>
		<h2 class="fs-title">Create your profile</h2>
		<%= f.input :first_name %>
		<%= f.input :last_name %>
		<%= f.input :birth_date %>
		<input type="button" name="next" class="next action-button" value="Next" />
	</fieldset>
	<fieldset>
		<h2 class="fs-title">Create your profile</h2>
		<%= f.input :address %>
		<%= f.input :zip_code %>
		<%= f.input :city %>
		<%= f.input :phone_number %>
		<input type="button" name="previous" class="previous action-button" value="Previous" />
		<input type="button" name="next" class="next action-button" value="Next" />
	</fieldset>
	<fieldset>
		<h2 class="fs-title">Create your profile</h2>
		<%= f.input :gender %>
		<%= f.input :totem %>
		<%= f.input :comment %>
		<%= f.input :photo, as: :attachinary %>
		<input type="button" name="previous" class="previous action-button" value="Previous" />
		<div class="form-actions">
			<%= f.button :submit %>
		</div>
	</fieldset>
	<% end %>
</div>

app/views/shared/_pending.html.erb
<div class="container" id="pendingcontainer">
  <div class="pendingbox text-center" >
    <h1>Sorry, your request of admission is still being processed</h1>
    <hr>
    <p>be sure to check your emails for news from us!</p>
    <h2>hope to see you soon!</h2>
  </div>
  </div>

app/views/shared/_signup.html.erb
<%= simple_form_for(resource, as: resource_name, html: {id: :msform}, url: registration_path(resource_name)) do |f| %>
<%= f.error_notification %>
<fieldset>
<h2>Sign up</h2>
<div class="form-inputs">
	
	<%= f.input :email, required: true, autofocus: true %>
	<%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
	<%= f.input :password_confirmation, required: true %>

</div>

<div class="form-actions">
	<%= f.button :submit, "Sign up" %>
	<%= render "devise/shared/links" %>
</div>
</fieldset>
<% end %>

app/views/shared/_taboo.html.erb
<div class="container taboo" >
  <div class="adminimg text-center"> <img src="<%=  image_path("baden.gif") %>" alt=""></div>
  <div class="pendingbox text-center" >
    <h1>OOOOPS LOOKS THAT THIS IS A TABOO ZONE</h1>
    <hr>
    <p>Please go play with the other children</p>
    <%= link_to "go back", profile_path(current_user.profile), class: "new-btn" %>
  </div>
  </div>