config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  get '/about' => 'pages#about'

  get 'children/index'

  get 'children/show'

  get 'children/create'

  get 'children/update'

  get 'sections/show'

  get 'sections/index'

  mount Attachinary::Engine => "/attachinary"

  get 'photos/new'

  get 'photos/create'

  get 'photos/update'

  get 'photos/edit'

  get 'photos/destroy'

  # devise_for :users
  devise_for :users, controllers: {
    registrations: "registrations", 
    sessions: "sessions"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :profiles, except: [:destroy]

  post 'global_search', to: 'invoices#index'

  resources :invoices, except: [:destroy] do
    member do
      post 'paid', to: 'invoices#paid'
      post 'unpaid', to: 'invoices#unpaid'
    end
    collection do
      post 'markaspaid'
    end
  end

  resources :events
  resources :albums
  resources :sections
  resources :children do
    member do
      post 'approve', to: 'children#approve'
    end
  end

  resources :messages, only: [:new, :create, :index]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :admin
  belongs_to :invoice, optional: true
  has_many :attendees
  belongs_to :profiles
  belongs_to :section

  validates :name, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :admin_id, presence: true

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_section_ids, only: [:create]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
    @event = Event.new
  end

  def show
  end

  def new
    @event = Event.new
  end

  def create
    @section_ids.each do |id|
      @success = create_event(id)
      break unless @success
    end
    if @event.save
      flash[:notice] = "Event successfully created"
      UserMailer.event(Profile.find(@event.profile_id).user, @event).deliver_now
      redirect_to events_path
    else
      flash[:notice] = "Event not created"
      render :new
    end
  end

  def edit
  end

  def update
    @event.update(event_params)
    redirect_to events_path
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def create_event(section_id)
    success = true
    Profile.where(section_id: section_id).each do |profile|
      if profile.user != current_user
        @event = Event.new(event_params)
        @event.admin = current_user.profile.admin
        @event.profile_id = profile.id
      end
    end
    success
  end

  def set_section_ids
    @section_ids = params.require(:sections)["section_ids"].reject { |x| x.blank? }
  end

  def event_params
    params.require(:event).permit(:name, :start_time, :end_time, :admin_id, :profile_id, :section)
  end
end

app/helpers/events_helper.rb
 module EventsHelper
   def events_ajax_previous_link
     ->(param, date_range) { link_to raw("&laquo;"), {param => date_range.first - 1.day}, remote: :true}
   end

   def events_ajax_next_link
     ->(param, date_range) { link_to raw("&raquo;"), {param => date_range.last + 1.day}, remote: :true}
    end
  end

app/views/events/edit.html.erb
<%= render 'shared/new-event' %>

app/views/events/index.html.erb
<% if current_user.profile.status == "Accepted" %>
  <h1 class="text-center">Events</h1>

  <main id="events" class=tab-box>

    <div class="tabs-bar">
      <!-- tabs -->
      <span>
        <button class="tabs-bar-item tab-button" onclick="openTab('upcoming-events')">Upcoming events</button>
        <button class="tabs-bar-item tab-button" onclick="openTab('past-events')">Past events</button>
      </span>

      <!-- Button trigger modal -->
      <button type="button" class="new-btn" data-toggle="modal" data-target="#newEventModal">
        <i class="fa fa-plus-circle" aria-hidden="true"></i>
      </button>

      <!-- Modal -->
      <div class="new-modal modal fade" id="newEventModal" tabindex="-1" role="dialog" aria-labelledby="newEventModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="newEventModalLabel">New event</h5>
              <button type="button" class="close close-btn" data-dismiss="modal" aria-label="Close">
                <i class="fa fa-times" aria-hidden="true"></i>
              </button>
            </div>
            <div class="modal-body">
              <%= render 'shared/new-event' %>
            </div>
          </div>
        </div>
      </div>

    </div>

    <div id="upcoming-events" class="tab">
      <h3>Upcoming events</h3>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Event Name</th>
            <th>Start Date</th>
            <th>End Date</th>
          </tr>
        </thead>
        <tbody><% @past_events = Event.where("start_time > ?", Time.now).each do |event| %>
          <tr class="clickable" data-toggle="collapse" id="<%= event.id %>" data-target=".<%= event.id %>collapsed">
            <td><%= event.name %></td>
            <td><%= event.start_time %></td>
            <td><%= event.end_time %></td>
            <td>
                    <!-- Butto  n trigger modal -->
              <button type="button" class="edit-btn blue" data-toggle="modal" data-target="#editEventModal-<%= event.id %>">
                <i class="fa fa-pencil" aria-hidden="true"></i>
              </button>

              <!-- Modal -->
              <div class="new-modal modal fade" id="editEventModal-<%= event.id %>" tabindex="-1" role="dialog" aria-labelledby="editEventModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="editEventModalLabel">Edit event</h5>
                      <button type="button" class="close close-btn" data-dismiss="modal" aria-label="Close">
                        <i class="fa fa-times" aria-hidden="true"></i>
                      </button>
                    </div>
                    <div class="modal-body">
                      <%= render 'shared/edit_event', event: event %>
                    </div>
                  </div>
                </div>
              </div>
            </td>

            <td>
              <%= link_to event_path(event.id), method: :delete, class:"btn-edit red", data: {confirm: "Are you sure you want to delete this event?"} do %>
                <i class="fa fa-minus-circle" aria-hidden="true"></i>
              <% end %>
            </td>
          </tr>
        <% end %></tbody>
      </table>
    </div>

    <div id="past-events" class="tab" style="display:none">
      <h3>Past events</h3>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Event Name</th>
            <th>Start Date</th>
            <th>End Date</th>
          </tr>
        </thead>
        <tbody><% @past_events = Event.where("start_time < ?", Time.now).each do |event| %>
          <tr class="clickable" data-toggle="collapse" id="<%= event.id %>" data-target=".<%= event.id %>collapsed">
            <td><%= event.name %></td>
            <td><%= event.start_time %></td>
            <td><%= event.end_time %></td>
          </tr>
        <% end %></tbody>
      </table>
    </div>

  </main>

  <div id="events-on-calendar">
    <%= month_calendar events: @events, previous_link: events_ajax_previous_link, next_link: events_ajax_next_link do |date, events| %>
       <%= date.day %>
     <% events.each do |event| %>
        <div>
          <%= event.name %>
          <%= event.description %>
      </div>
      <% end %>
    <% end %>
  </div>
<% else %>

<%= render "shared/pending" %>
<% end %>

app/views/events/new.html.erb
<% if current_user.profile.admin %>
<%= render 'shared/new-event' %>
<% else %>
<%= render 'shared/taboo' %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<div class="form-group btn-div">
  <%= link_to 'Edit the event info', edit_event_path, class: "btn btn-primary" %>
  <%= link_to 'Back to all events', events_path, class:"btn btn-primary" %>
</div>